FMAX: 16000
FMIN: 20
FS: 32000
HOP_LENGTH: 512
MINMAX_NORM: true
N_FFT: 2048
N_MELS: 256
OUTPUT_DIR: ../output
TARGET_DURATION: 5.0
TARGET_SHAPE:
- 256
- 256
T_max: 10
aug_prob: 0.6
batch_size: 128
brightness: true
criterion: BCEWithLogitsLoss
crop_position: middle
debug: false
device: cuda
drop_path_rate: 0.2
drop_rate: 0.2
epochs: 10
filter_voice: false
filter_voice_method: none
in_channels: 1
lr: 0.003
min_lr: 1.0e-06
mixup_alpha: 0.6
model_name: efficientnet_b0
n_fold: 5
num_workers: 0
optimizer: AdamW
precompute_audio: true
precomputed_filename: melspec.npy
precomputerd_datadir: ../input/birdclef-2025-precomputed
pretrained: true
scheduler: CosineAnnealingLR
seed: 2025
selected_folds:
- 0
submission_csv: ../input/birdclef-2025/sample_submission.csv
taxonomy_csv: ../input/birdclef-2025/taxonomy.csv
test_soundscapes: ../input/birdclef-2025/test_soundscapes
train_csv: ../input/birdclef-2025/train.csv
train_datadir: ../input/birdclef-2025/train_audio
voice_datadir: ../input/voice_data
weight_decay: 0.01
